public class Main {
    public static void main(String[] args) {
        System.out.println("Домашнее задание 2");
        System.out.println("         Задача 1");
        var dog = 8.0 ;
        var cat = 3.6 ;
        var paper = 763789 ;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("         Задача 2");
        dog = dog + 4 ;
        cat = cat + 4 ;
        paper = paper + 4 ;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("         Задача 3");
        dog = dog - 3.5 ;
        cat = cat - 1.6 ;
        paper = paper - 7639 ;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("         Задача 4");
        var friend = 19 ;
        System.out.println(friend);
        friend = friend * 2 ;
        System.out.println(friend);
        friend = friend / 7 ;
        System.out.println(friend);
        System.out.println("         Задача 5");
        var frog = 3.5 ;
        System.out.println(frog);
        frog = frog * 10 ;
        System.out.println(frog);
        frog = frog / 3.5 ;
        System.out.println(frog);
        frog = frog + 4 ;
        System.out.println(frog);
        System.out.println("         Задача 6");
        var boxer1Mass = 78.2 ;
        System.out.println(boxer1Mass);
        var boxer2Mass = 82.7 ;
        System.out.println(boxer2Mass);
        var boxerSum =  0.0 ;
        var boxerDiff = 0.0 ;
        boxerSum = boxer1Mass + boxer2Mass ;
        System.out.println(boxerSum);
        boxerDiff = boxer2Mass - boxer1Mass ;
        System.out.println(boxerDiff);
        System.out.println("         Задача 7");
        boxerDiff = boxer2Mass - boxer1Mass ;
        System.out.println(boxerDiff);
        boxerDiff = boxer2Mass % boxer1Mass ;
        System.out.println(boxerDiff);
        System.out.println("         Задача 8");
        System.out.println("          Часть 1");
        var employeeNum = 0 ;
        var employeeDayTime = 8 ;
        var employeeTime = 640 ;
        employeeNum = employeeTime / employeeDayTime ;
        System.out.println("Всего работников в компании - " + employeeNum + " человек");
        System.out.println("          Часть 2");
        employeeNum = employeeNum + 94 ;
        employeeTime = employeeNum * employeeDayTime ;
        System.out.println("Если в компании работает " + employeeNum + " человек,"
                + " то всего " + employeeTime + " часов работы может быть поделено между сотрудниками");
    }
}